# @package _global_
defaults:
  - /decode/se_dicow_beam_joint

experiment: "2_25"

data:
  number_of_mixed_speakers: 2
  min_enrollment_mix_overlap: 0.25
  max_enrollment_mix_overlap: 0.25
  eval_cutsets:
    - ${oc.env:MANIFEST_DIR}/librimix/librimix_cutset_libri3mix_test-clean.jsonl_external_enrollment.gz

wandb:
 project: "enrollment_ablations"
