# @package _global_
defaults:
  - /decode/se_dicow_beam_joint

experiment: "clean"

data:
  number_of_mixed_speakers: 0
  min_enrollment_mix_overlap: 0
  max_enrollment_mix_overlap: 0
  eval_cutsets:
    - ${oc.env:MANIFEST_DIR}/librimix/librimix_cutset_libri3mix_test-clean.jsonl_external_enrollment.gz

wandb:
 project: "enrollment_ablations"
