# @package _global_
defaults:
  - /decode/se_dicow_greedy

experiment: "SE_DiCoW_beam_joint"

training:
  generation_num_beams: 5
  per_device_eval_batch_size: 2

decoding:
  decoding_ctc_weight: 0.2
  length_penalty: 0.1

