# @package _global_
defaults:
  - /train/dicow_v3

experiment: wo_aug

aug:
  stno_gaussian_noise_prob: 0.0
  stno_segment_augment_prob: 0.0
  stno_segment_change_prob: 0.0
  spec_aug_prob: 0.0
  musan_root: ${oc.env:MUSAN_ROOT}
  musan_augment_prob: 0.0